# Generated by Django 4.1.1 on 2022-09-18 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.brandmanagement', verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.colormanagement', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.categorymanagement', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.statusmanagement', verbose_name='Статус'),
        ),
    ]
